### PR TITLE
Add support for Sphinx 2.0

### PR DESCRIPTION
**Pull request by stephenfin**

### CODE REVIEW

**Comment by stephenfin** [comment]
The tests are failing without this changes. Any ideas, @kallimachos ?

**Comment by kallimachos** [comment]
Thanks for the PR @stephenfin. I'll dig into the logs tomorrow and see if I can figure out why the tests are failing.

**Comment by stephenfin** [comment]
Thanks. Let me know if there's anything I can do to help.

On a side note, I don't know if you've any interest in moving this to the @sphinx-contrib organization. Could help with the maintenance burden. Let me know (here or via email) if you do

**Comment by kallimachos** [comment]
Hi @stephenfin. I'm still working on this. A couple of things to start though:

- It looks like Sphinx 2.0 does not support Python 2.7. I'd like Sphinxmark to drop 2.7 support as well, so long as that works for your environment.
- I'm happy to move the extension into @sphinx-contrib, if you think that makes sense. We'll get this PR sorted out first, then we can move it over.

**Comment by stephenfin** [comment]
Python 3-only is good as is moving the extension once all this is resolved

**Comment by kallimachos** [comment]
@stephenfin I think that's got it. If it looks good to you, I'll go ahead and merge.

**Comment by stephenfin** [comment]
Looks good to me, yup

**Pull request merged**
